### ISSUE TITLE
Problem to run a simple motor program

### ISSUE THREAD

**Issue by natrodrigues** [ddemidov/ev3dev-lang-cpp#50]
Hello!

I am trying to code a simple C++ program for large motors but it seems ev3 can't connect it. I am trying this simple code:

```
#include<bits/stdc++.h>
#include "ev3dev.h"

using namespace std;
namespace ev3 = ev3dev;

void precondition(bool cond, const std::string &msg) {
    if (!cond) throw std::runtime_error(msg);
}

int main(){

        ev3::large_motor leftMotor(ev3::OUTPUT_B);
        ev3::large_motor rightMotor(ev3::OUTPUT_C);

        precondition(leftMotor.connected(), "motor no outB nao conectado");
        precondition(rightMotor.connected(), "motor no outC nao conectado");

        while(!ev3::button::back.pressed()){
                rightMotor.run_forever();
                leftMotor.run_forever();
        }

        return 0;
}
```
The error is:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  motor no outB nao conectado
Aborted
```
But I checked the ports on the EV3 itself and it was okay. 

Fortunally, I can compile and run simple programs using sensors only.

I'd be very grateful if anyone can help me!

**Comment by ddemidov** [comment]
Most likely the problem is that the values of `OUTPUT` constants are out of sync with the ev3dev version you are using. You can check that by connecting a motor to ev3 and checking the output of the following shell command on the ev3:
```
cat /sys/class/lego/tacho-motor/motor*/address
```
If you get values that differ from these:

https://github.com/ddemidov/ev3dev-lang-cpp/blob/b0331bca988dc78e23a349e8d6b47ce695eb91d9/ev3dev.h#L98-L101

then you can use the values directly instead of the `OUTPUT` constants.

**Comment by natrodrigues** [comment]
Thanks, @ddemidov ! It was really this issue. In my EV3 version, the ports are ```outB``` for example.
Additionally, I had to change a little bit to run the motors. Just run_forever doesn't work, I had to put ```motor.set_speed_sp(200).run_forever();```. Thanks a lot!
